### GET request
GET http://localhost:8000



### POST user request
POST http://localhost:8000
Content-Type: application/json

{ 
    "id": "4",
    "fName": "Santoshi",
    "lName": "Lc"
}
### PUT user request
PUT http://localhost:8000
Content-Type: application/json
Authorization: T0KeN2Runa11

{ 
    "id": "2",
    "fName": "Nismo"
}
### DELETE user request
DELETE http://localhost:8000/4
